//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;



/// <remarks/>

[System.Web.Services.WebServiceAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
    "xGatewayWebService/1.0")]
[System.Web.Services.WebServiceBindingAttribute(Name = "SendFAXGatewayHttpBinding", Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
    "xGatewayWebService/1.0")]
public class SendFAXGatewayHttpService : System.Web.Services.WebService
{

    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("SendFAXResponse", Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
        "xGatewayWebService/1.0")]
    public SendFAXResponse SendFAX([System.Xml.Serialization.XmlElementAttribute("SendFAX", Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
        "xGatewayWebService/1.0")] SendFAX SendFAX1)
    {

        var path = Server.MapPath("~");


        var documents = SendFAX1.SendOutboundFAX.Documents;

        foreach (var doc in documents)
        {
            switch (doc.DocumentType)
            {
                case DocumentType.PDF:
                    File.WriteAllBytes(path + "myexample.pdf", doc.DocumentContent);
                    break;
                case DocumentType.xHTML:
                    break;
                case DocumentType.MSDOC:
                    break;
                default:
                    break;
            }
        }


        return new SendFAXResponse();
    }
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
    "xGatewayWebService/1.0")]
public class SendFAX
{

    private SendOutboundFAXType sendOutboundFAXField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public SendOutboundFAXType SendOutboundFAX
    {
        get
        {
            return this.sendOutboundFAXField;
        }
        set
        {
            this.sendOutboundFAXField = value;
        }
    }
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public partial class SendOutboundFAXType
{

    private string userNameField;

    private string passWordField;

    private string destinationField;

    private string priorityField;

    private string receiptField;

    private string senderField;

    private string faxRequestDateTimeField;

    private Document[] documentsField;

    /// <remarks/>
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }

    /// <remarks/>
    public string PassWord
    {
        get
        {
            return this.passWordField;
        }
        set
        {
            this.passWordField = value;
        }
    }

    /// <remarks/>
    public string Destination
    {
        get
        {
            return this.destinationField;
        }
        set
        {
            this.destinationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
    public string Priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }

    /// <remarks/>
    public string Receipt
    {
        get
        {
            return this.receiptField;
        }
        set
        {
            this.receiptField = value;
        }
    }

    /// <remarks/>
    public string Sender
    {
        get
        {
            return this.senderField;
        }
        set
        {
            this.senderField = value;
        }
    }

    /// <remarks/>
    public string FaxRequestDateTime
    {
        get
        {
            return this.faxRequestDateTimeField;
        }
        set
        {
            this.faxRequestDateTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public Document[] Documents
    {
        get
        {
            return this.documentsField;
        }
        set
        {
            this.documentsField = value;
        }
    }
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public partial class Document
{

    private string seqNumberField;

    private string documentIdField;

    private DocumentType documentTypeField;

    private byte[] documentContentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
    public string SeqNumber
    {
        get
        {
            return this.seqNumberField;
        }
        set
        {
            this.seqNumberField = value;
        }
    }

    /// <remarks/>
    public string DocumentId
    {
        get
        {
            return this.documentIdField;
        }
        set
        {
            this.documentIdField = value;
        }
    }

    /// <remarks/>
    public DocumentType DocumentType
    {
        get
        {
            return this.documentTypeField;
        }
        set
        {
            this.documentTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] DocumentContent
    {
        get
        {
            return this.documentContentField;
        }
        set
        {
            this.documentContentField = value;
        }
    }
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public enum DocumentType
{

    /// <remarks/>
    PDF,

    /// <remarks/>
    xHTML,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("MS-DOC")]
    MSDOC,
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public partial class SendOutboundFAXAckType
{

    private string transactionRefField;

    private OutcomeType outcomeField;

    private string errorCodeField;

    private string errorTextField;

    /// <remarks/>
    public string TransactionRef
    {
        get
        {
            return this.transactionRefField;
        }
        set
        {
            this.transactionRefField = value;
        }
    }

    /// <remarks/>
    public OutcomeType Outcome
    {
        get
        {
            return this.outcomeField;
        }
        set
        {
            this.outcomeField = value;
        }
    }

    /// <remarks/>
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }

    /// <remarks/>
    public string ErrorText
    {
        get
        {
            return this.errorTextField;
        }
        set
        {
            this.errorTextField = value;
        }
    }
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
    "eway/1.0")]
public enum OutcomeType
{

    /// <remarks/>
    Success,

    /// <remarks/>
    Failure,

    /// <remarks/>
    Acknowledge,
}

/// <remarks/>

[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
    "xGatewayWebService/1.0")]
public partial class SendFAXResponse
{

    private SendOutboundFAXAckType sendOutboundFAXAckField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public SendOutboundFAXAckType SendOutboundFAXAck
    {
        get
        {
            return this.sendOutboundFAXAckField;
        }
        set
        {
            this.sendOutboundFAXAckField = value;
        }
    }
}
